import { Footer, Navbar } from '@/components';
import { Provider } from '@/components/ui/provider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bioiglesia',
  description: 'Generated by create next app',
  icons: {
    icon: '/logobioiglesia.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body>
        <Provider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
